name: hola-mundo
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        id: cp
        uses: actions/checkout@v3
      - name: Install Python3
        id: ip3
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Hola Mundo from Python3
        id: hmfp3
        run: python3 holamundo.py